### ISSUE TITLE
Cannot find libstdc++ inside Docker container

### ISSUE THREAD

**Issue by eightyeight** [bos/double-conversion#11]
When trying to use this library inside one of the Haskell Docker containers:

```
$ docker run -ti --rm -v `pwd`:/code haskell:7.10 /bin/bash
# cd /code
# cabal update
# cabal sandbox init
# cabal install double-conversion
...
Configuring double-conversion-2.0.1.0...
setup-Simple-Cabal-1.22.2.0-x86_64-linux-ghc-7.10.1: Missing dependency on a
foreign library:
* Missing C library: stdc++
```

I fixed this by running, inside the container,
```
# ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/lib/libstdc++.so
# apt-get install g++
```

Is this something that should be documented somewhere?

**Comment by brsunter** [comment]
I also encountered this problem. I'm pretty new at Docker so I'm not sure if this is the right place for this, but I was also able to fix it by "apt-get install g++" on the container (did not need to symlink)

Probably the haskell:7.10 docker image not including  c++ ?

**Comment by eightyeight** [comment]
Ah right, I tried the symlink first and it changed the error message so I assumed it was a step in the right direction haha. Maybe we should file this issue against the Docker Haskell repo.

**Comment by bos** [comment]
Sorry folks, this is not an issue with this library.

**Comment by eightyeight** [comment]
Yup, should have closed this. Sorry to bother!
