### ISSUE TITLE
probable array overwrite in toShortest

### ISSUE THREAD

**Issue by rwbarton** [bos/double-conversion#9]
Hi,

I was investigating a GHC bug report and came to the conclusion that the panic was caused by a write past the end of an allocated array by this `double-conversion` library. However, the reproducer is a project with several modules and it takes quite a few hours to crash, so you'd probably have an easier time reproducing the issue from scratch.

See https://ghc.haskell.org/trac/ghc/ticket/10154#comment:8.

Based on the evidence there it seems most likely that

```
static const int kToShortestLength = 24;
```

is not enough, since the mutable byte array that got overflowed was of size 0x30 = 24*2 bytes, but 25 UTF-16 code points were copied to the array.

**Comment by brk** [comment]
I ran into this segfault today. Here's a very small testcase:

```
$ cat Test.hs
{-# LANGUAGE BangPatterns #-}
module Test where

import Data.Text()
import Data.Double.Conversion.Text(toShortest)

main = do
  let val = -2.9658956854023756e-5
  putStrLn $ "(toShortest " ++ show val ++ ") ="
  let !shortS = toShortest val
  putStrLn $ "  ...   " -- Won't get printed.
  putStrLn $ show shortS
$ cabal exec -- runhaskell Test.hs
(toShortest -2.9658956854023756e-5) =
Segmentation fault (core dumped)
```

**Comment by bos** [comment]
Cheers, all fixed up.
